#include "\x\cba\addons\main\script_macros_common.hpp"

#define SAA_LOG(MESSAGE) 										private _logMessage = format ["SAA %1",MESSAGE]; diag_log _logMessage; systemChat _logMessage;

#define SAA_DEBUG(MESSAGE) 										if (SAA_setting_debug) then {SAA_LOG(FORMAT_1("Debug: %1",MESSAGE))};
#define SAA_DEBUG_1(MESSAGE,ARG1) 								SAA_DEBUG(FORMAT_1(MESSAGE,ARG1))
#define SAA_DEBUG_2(MESSAGE,ARG1,ARG2) 							SAA_DEBUG(FORMAT_2(MESSAGE,ARG1,ARG2))
#define SAA_DEBUG_3(MESSAGE,ARG1,ARG2,ARG3) 					SAA_DEBUG(FORMAT_3(MESSAGE,ARG1,ARG2,ARG3))
#define SAA_DEBUG_4(MESSAGE,ARG1,ARG2,ARG3,ARG4) 				SAA_DEBUG(FORMAT_4(MESSAGE,ARG1,ARG2,ARG3,ARG4))
#define SAA_DEBUG_5(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5) 			SAA_DEBUG(FORMAT_5(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5))

#define SAA_ERROR(MESSAGE) 										SAA_LOG(FORMAT_1("Error: %1",MESSAGE))
#define SAA_ERROR_1(MESSAGE,ARG1) 								SAA_ERROR(FORMAT_1(MESSAGE,ARG1))
#define SAA_ERROR_2(MESSAGE,ARG1,ARG2) 							SAA_ERROR(FORMAT_2(MESSAGE,ARG1,ARG2))
#define SAA_ERROR_3(MESSAGE,ARG1,ARG2,ARG3) 					SAA_ERROR(FORMAT_3(MESSAGE,ARG1,ARG2,ARG3))
#define SAA_ERROR_4(MESSAGE,ARG1,ARG2,ARG3,ARG4) 				SAA_ERROR(FORMAT_4(MESSAGE,ARG1,ARG2,ARG3,ARG4))
#define SAA_ERROR_5(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5) 			SAA_ERROR(FORMAT_5(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5))

#define SAA_WARNING(MESSAGE) 									SAA_LOG(FORMAT_1("Warning: %1",MESSAGE))
#define SAA_WARNING_1(MESSAGE,ARG1) 							SAA_ERROR(FORMAT_1(MESSAGE,ARG1))
#define SAA_WARNING_2(MESSAGE,ARG1,ARG2) 						SAA_ERROR(FORMAT_2(MESSAGE,ARG1,ARG2))
#define SAA_WARNING_3(MESSAGE,ARG1,ARG2,ARG3) 					SAA_ERROR(FORMAT_3(MESSAGE,ARG1,ARG2,ARG3))
#define SAA_WARNING_4(MESSAGE,ARG1,ARG2,ARG3,ARG4) 				SAA_ERROR(FORMAT_4(MESSAGE,ARG1,ARG2,ARG3,ARG4))
#define SAA_WARNING_5(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5) 		SAA_ERROR(FORMAT_5(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5))
